views/home_views.py
import flask

home_blueprint = flask.Blueprint("home", __name__, template_folder="templates")


@home_blueprint.route("/")
def home():
    return flask.render_template("home/home.html")

views/login_views.py
from flask import current_app, Blueprint, url_for, redirect, request, render_template, flash
from forms.login import LoginForm
from models.models import UserModel
from flask_login import login_user, current_user, logout_user
from app import db

blueprint = Blueprint("user", __name__, template_folder="templates")


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("feedback.feedback"))
    form = LoginForm()

    if form.validate_on_submit():
        user = UserModel.query.filter_by(email=form.email.data.lower()).first()
        if user and UserModel.verify_password(form.password.data, user.password):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            if next_page:
                return redirect(next_page)
            return redirect(url_for("feedback.feedback"))
        else:
            flash(f"Please check your credentials", "danger")
    return render_template("user/login.html", form=form)


@blueprint.route("/logout")
def logout():
    # Before logging out, set the feedback flag in the UserModel model to N
    user = UserModel.query.filter_by(id=current_user.id).first()
    user.feedback = "N"
    db.session.commit()

    logout_user()

    return redirect(url_for("home.home"))

templates/shared/_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <title>Farm Fresh Produce</title>
        <link rel="icon" href="../../static/images/logo.jpg">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="../../static/css/common.css">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}
</head>
<body>
    <!-- Nav -->
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('home.home') }}">
            <img class="nav-logo" src="../../static/images/logo.jpg" alt="">
        </a>

        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Sign Out</a>
                </li>
            {% endif %}
        </ul>
    </nav>

    <!-- Logo -->
    <div class = "logo">
        <img class ="logo" alt="logo" src="../../static/images/logo.ico">
    </div>

    <!-- Jumbotron -->
{#    <div class="jumbotron">#}
{#        <div class="container">#}
{#            <img alt="produce" src="../../static/images/jumbo.jpg">#}
{#        </div>#}
{#    </div>#}
    <div class="flash-container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%  if messages %}
                {% for category, message in messages %}
                    <div class="alert-{{ category }}">
                        <span>{{ message }}</span>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>

    {% block content %}
    {% endblock content %}

    <br/>
    <br/>
    <footer class="site-footer">
        Made with <span><img alt="heart" src="../../static/images/love.ico"></span> in Bangalore
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Font Awesome goes here -->
    <script src="https://kit.fontawesome.com/5ceb4d3475.js"></script>
</body>
</html>