forms/login.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, SubmitField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Email, Length


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8, max=20)])
    remember = BooleanField("Remember Me")
    recaptcha = RecaptchaField()
    submit = SubmitField("Sign In")

forms/register.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class RegisterForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8, max=20)])
    confirm_password = PasswordField("Confirm Password", validators=[DataRequired(), EqualTo("password")])
    submit = SubmitField("Sign Up")

views/login_views.py
from flask import current_app, Blueprint, url_for, redirect, request, render_template, flash
from forms.login import LoginForm
from models.models import UserModel
from flask_login import login_user, current_user, logout_user
from app import db

blueprint = Blueprint("user", __name__, template_folder="templates")


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("feedback.feedback"))
    form = LoginForm()

    if form.validate_on_submit():
        user = UserModel.query.filter_by(email=form.email.data.lower()).first()
        if user and UserModel.verify_password(form.password.data, user.password):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            if next_page:
                return redirect(next_page)
            return redirect(url_for("feedback.feedback"))
        else:
            flash(f"Please check your credentials", "danger")
    return render_template("user/login.html", form=form)


@blueprint.route("/logout")
def logout():
    # Before logging out, set the feedback flag in the UserModel model to N
    user = UserModel.query.filter_by(id=current_user.id).first()
    user.feedback = "N"
    db.session.commit()

    logout_user()

    return redirect(url_for("home.home"))

views/register_views.py
import flask
import app
from forms.register import RegisterForm
from models.models import UserModel
from flask_login import current_user

blueprint = flask.Blueprint("register", __name__, template_folder="templates")


@blueprint.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return flask.redirect(flask.url_for("feedback.feedback"))

    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = UserModel.hash_password(form.password.data)
        user = UserModel(name=form.name.data, email=form.email.data.lower(), password=hashed_password)

        if UserModel.verify_email(form.email.data):
            flask.flash("An account with this email already exists", "danger")
        else:
            try:
                app.db.session.add(user)
                app.db.session.commit()
                flask.flash(f"The account for {form.email.data} has been created", "success")
                return flask.redirect(flask.url_for("user.login"))
            except Exception as e: # pragma: no cover
                print(e)
    return flask.render_template("user/register.html", form=form)

templates/user/login.html
{% extends "shared/_layout.html" %}
{%  block head %}
    {{ super() }}
{%  endblock head %}

{% block content %}
    <div class="container-wrapper">
        <div class="container-fluid">
            <form method="post" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Sign In</legend>
                    <div class="form-group">
                        {{ form.email.label }}

                        {% if form.email.errors %}
                            {{ form.email(class="form-control is-invalid") }}
                            {% for error in form.email.errors %}
                                <div class="invalid-feedback">
                                    <span>{{ error }}</span>
                                </div>
                            {% endfor %}
                        {% else %}
                            {{ form.email(class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="from-group">
                        {{ form.password.label }}

                        {% if form.password.errors %}
                            {{ form.password(class="form-control is-invalid") }}
                            {% for error in form.password.errors %}
                                <div class="invalid-feedback">
                                    <span>{{ error }}</span>
                                </div>
                            {% endfor %}
                        {% else %}
                            {{ form.password(class="form-control") }}
                        {% endif %}
                    </div>
                    <br/>
                    <div class="from-group">
                        <div class="form-check">
                            {{ form.remember(class="form-check-input") }}
                            {{ form.remember.label(class="form-check-label") }}
                        </div>
                    </div>
                    <br/>
                    {{ form.recaptcha }}
                    {% for error in form.recaptcha.errors %}
                        <div style="font-family: 'Calibri'; font-size: medium ;color: crimson">{{ error }}</div>
                    {% endfor %}
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-dark btn-block") }}
                </div>
                <div class="alt-login">
                    <div class="form-group">
                        Don't have an account? <a href="{{  url_for('register.register') }}">Sign Up</a>
                    </div>
                    <div class="form-group">
                        or you can sign in with
                        <a href="#"><i style="color: red" class="fab fa-google"></i></a>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

templates/user/register.html
{% extends "./shared/_layout.html" %}

{% block head %}
    {{ super() }}
{% endblock head %}

{% block content %}
    <div class="container-wrapper">
        <div class="container">
            <form method="post" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Register Now!</legend>
                    <div class="form-group">
                        {{ form.name.label }}

                        {% if form.name.errors %}
                            {{ form.name(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                         {% else %}
                            {{ form.name(class="form-control") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.email.label }}

                        {% if form.email.errors %}
                            {{ form.email(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.password.label }}

                        {% if form.password.errors %}
                            {{ form.password(class="form-control is-invalid") }}
                            {% for error in form.password.errors %}
                                <div class="invalid-feedback">
                                    <span>{{ error }}</span>
                                </div>
                            {% endfor %}
                        {% else %}
                            {{ form.password(class="form-control") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.confirm_password.label }}

                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class="form-control is-invalid") }}
                            {% for error in form.confirm_password.errors %}
                                <div class="invalid-feedback">
                                    <span>{{ error }}</span>
                                </div>
                            {% endfor %}
                        {% else %}
                            {{ form.confirm_password(class="form-control") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-dark btn-block") }}
                </div>
                <div class="alt-login">
                    <div class="form-group">
                        Have an account? <a href="{{  url_for('user.login') }}">Sign In</a>
                    </div>
                    <div class="form-group">
                        or you can sign in with
                        <a href="#"><i style="color: red" class="fab fa-google"></i></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}